### ISSUE TITLE
我使用单个卡进行训练，cuda内存不足，于是我增加了一个卡，就出现报错，我应该如何修改呢？

### ISSUE THREAD

**Issue by zhouinging** [gswycf/SignGraph#17]
(sg) zxn@ubun:/media/ExtHDD2/zxn/project/SignGraph-main$ python main.py --load-weights best_model.pt --phase test
Not using distributed mode
[0, 1]
Loading model
/media/ExtHDD2/zxn/Anaconda3/envs/sg/lib/python3.8/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
main.py:180: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(weight_path)
using dataparalleling...
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    processor = Processor(args)
  File "main.py", line 49, in __init__
    self.model, self.optimizer = self.loading()
  File "main.py", line 163, in loading
    model = self.model_to_device(model)
  File "main.py", line 172, in model_to_device
    model = nn.SyncBatchNorm.convert_sync_batchnorm(model.to(self.arg.local_rank))
  File "/media/ExtHDD2/zxn/Anaconda3/envs/sg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1138, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Device index must not be negative

**Comment by gswycf** [comment]
Hi, try this command: python main.py --device "0,1" --load-weights best_model.pt --phase test

**Comment by zhouinging** [comment]
(sg) zxn@ubun:/media/ExtHDD2/zxn/project/SignGraph-main$ python main.py --device "0,1" --load-weights best_model.pt --phase test
Not using distributed mode
[0, 1]
Loading model
/media/ExtHDD2/zxn/Anaconda3/envs/sg/lib/python3.8/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
main.py:180: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(weight_path)
using dataparalleling...
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    processor = Processor(args)
  File "main.py", line 49, in __init__
    self.model, self.optimizer = self.loading()
  File "main.py", line 163, in loading
    model = self.model_to_device(model)
  File "main.py", line 172, in model_to_device
    model = nn.SyncBatchNorm.convert_sync_batchnorm(model.to(self.arg.local_rank))
  File "/media/ExtHDD2/zxn/Anaconda3/envs/sg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1138, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Device index must not be negative
还是没有变化

**Comment by gswycf** [comment]
python main.py --device 0,1 --load-weights best_model.pt --phase test

how about this? Can you print "self.arg.local_rank”， make sure it>=0

**Comment by zhouinging** [comment]
这个也是一样的错误，我不懂如何打印？

**Comment by gswycf** [comment]
Just try to add "print(self.arg.loacl_rank)" before 
"model = nn.SyncBatchNorm.convert_sync_batchnorm(model.to(self.arg.local_rank))"

**Comment by zhouinging** [comment]
打印结果为-1

**Comment by gswycf** [comment]
Hi, I update parameters.py, you can download and try it again. If it still doesn't work, try to change "model = nn.SyncBatchNorm.convert_sync_batchnorm(model.to(self.arg.local_rank))" to "model = nn.SyncBatchNorm.convert_sync_batchnorm(model)". 
Hope you best

**Comment by zhouinging** [comment]
(sg) zxn@ubun:/media/ExtHDD2/zxn/project/SignGraph-main$ python main.py --device 0,1 --load-weights best_model.pt --test
usage: main.py [-h] [--work-dir WORK_DIR] [--config CONFIG] [--random_fix RANDOM_FIX] [--device DEVICE] [--phase PHASE] [--save-interval SAVE_INTERVAL] [--random-seed RANDOM_SEED]
               [--eval-interval EVAL_INTERVAL] [--print-log PRINT_LOG] [--log-interval LOG_INTERVAL] [--evaluate-tool EVALUATE_TOOL] [--feeder FEEDER] [--dataset DATASET] [--dataset-info DATASET_INFO]
               [--num-worker NUM_WORKER] [--feeder-args FEEDER_ARGS] [--model MODEL] [--model-args MODEL_ARGS] [--load-weights LOAD_WEIGHTS] [--load-checkpoints LOAD_CHECKPOINTS]
               [--decode-mode DECODE_MODE] [--ignore-weights IGNORE_WEIGHTS [IGNORE_WEIGHTS ...]] [--batch-size BATCH_SIZE] [--test-batch-size TEST_BATCH_SIZE] [--loss-weights LOSS_WEIGHTS]
               [--optimizer-args OPTIMIZER_ARGS] [--num-epoch NUM_EPOCH] [--world-size WORLD_SIZE] [--local_rank LOCAL_RANK] [--dist-url DIST_URL]
main.py: error: argument --test-batch-size: expected one argument
更新相关文件后遇到这个问题，我尝试运行了python main.py --device 0,1 --load-weights best_model.pt --test --test-batch-size 32
但错误仍然是main.py: error: argument --test-batch-size: expected one argument

**Comment by gswycf** [comment]
Sorry for the late reponse,  "python main.py --device 0,1 --load-weights best_model.pt --test  --test-batch-size 32" should be fine. You can also try change 
test_batch_size in baseline.yaml. If it work, i still think that test_batch_size=32 is too large for the GPU memory.

**Comment by zhouinging** [comment]
(sg) zxn@ubun:/media/ExtHDD2/zxn/project/SignGraph-main$ python main.py --device 0,1 --load-weights best_model.pt --test
usage: main.py [-h] [--work-dir WORK_DIR] [--config CONFIG] [--random_fix RANDOM_FIX] [--device DEVICE] [--phase PHASE]
               [--save-interval SAVE_INTERVAL] [--random-seed RANDOM_SEED] [--eval-interval EVAL_INTERVAL]
               [--print-log PRINT_LOG] [--log-interval LOG_INTERVAL] [--evaluate-tool EVALUATE_TOOL] [--feeder FEEDER]
               [--dataset DATASET] [--dataset-info DATASET_INFO] [--num-worker NUM_WORKER] [--feeder-args FEEDER_ARGS]
               [--model MODEL] [--model-args MODEL_ARGS] [--load-weights LOAD_WEIGHTS] [--load-checkpoints LOAD_CHECKPOINTS]
               [--decode-mode DECODE_MODE] [--ignore-weights IGNORE_WEIGHTS [IGNORE_WEIGHTS ...]] [--batch-size BATCH_SIZE]
               [--test-batch-size TEST_BATCH_SIZE] [--loss-weights LOSS_WEIGHTS] [--optimizer-args OPTIMIZER_ARGS]
               [--num-epoch NUM_EPOCH] [--world-size WORLD_SIZE] [--local_rank LOCAL_RANK] [--dist-url DIST_URL]
main.py: error: argument --test-batch-size: expected one argument
你好，我修改以后仍然报错，我现在还没找到解决办法

**Comment by gswycf** [comment]
Try "python main.py --device 0,1 --load-weights best_model.pt --phase test"  change test_batch_size in config.yaml
