### ISSUE TITLE
我在多卡训练时遇到了没有正确初始化默认的进程组（process group）的报错

### ISSUE THREAD

**Issue by Galaxy0422** [gswycf/SignGraph#18]
/sdb1/userdata/mhy/anaconda3/envs/pytorch/bin/python3.8 /sdb1/userdata/mhy/SignGraph-main/main.py 
Not using distributed mode
[0, 1, 2, 3]
Loading model
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
using dataparalleling...
Traceback (most recent call last):
  File "/sdb1/userdata/mhy/SignGraph-main/main.py", line 304, in <module>
    processor = Processor(args)
  File "/sdb1/userdata/mhy/SignGraph-main/main.py", line 49, in __init__
    self.model, self.optimizer = self.loading()
  File "/sdb1/userdata/mhy/SignGraph-main/main.py", line 163, in loading
    model = self.model_to_device(model)
  File "/sdb1/userdata/mhy/SignGraph-main/main.py", line 174, in model_to_device
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[self.arg.local_rank])
  File "/sdb1/userdata/mhy/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 595, in __init__
    self.process_group = _get_default_group()
  File "/sdb1/userdata/mhy/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

进程已结束，退出代码为 1

**Comment by gswycf** [comment]
Not using distributed mode
[0, 1, 2, 3]
Loading model

hi, the log shows that you are not using  distributed mode, while still adopt mutil GPU, that is why you get this erro. Can you show your command?

**Comment by Galaxy0422** [comment]
I used this command    "python main.py --device 0,1,2,3"

**Comment by gswycf** [comment]
Hi, to run mutliGPU trianing, you can try: "python -m torch.distributed.launch --nproc_per_node=4 --use_env --device 0,1,2,3", or torchrun -nproc_per_node=4 --use_env --device 0,1,2,3. But i never test muitple GPU training, so this code may not work very well on  mutilpe GPUs.

**Comment by Galaxy0422** [comment]
Thank you for your reply. I used the command "python -m torch.distributed.launch --nproc_per_node=4 --use_env --device 0,1,2,3", but it gave the error "launch.py: error: unrecognized arguments: --device". Therefore, I used "python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py" instead. It seems the code is running normally, but after waiting for 20 minutes, it is still stuck on the following screen:

**Comment by Galaxy0422** [comment]
Thank you for your reply.            I used the command "python -m torch.distributed.launch --nproc_per_node=4 --use_env --device 0,1,2,3", but it gave the error "launch.py: error: unrecognized arguments: --device".  Therefore, I used "python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py" instead. It seems the code is running normally, but after waiting for 20 minutes, it is still stuck on the following screen:                                                                                             
(pytorch) mhy@lgdx-X785-H30:/sdb1/userdata/mhy/SignGraph-main$ python -m torch.distributed.launch --nproc_per_node=4 --use_env main.py
/sdb1/userdata/mhy/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 2): env://, gpu 2
| distributed init (rank 1): env://, gpu 1
| distributed init (rank 3): env://, gpu 3
[0, 1, 2, 3]
Loading model
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
using dataparalleling...

**Comment by gswycf** [comment]
Like i said, this code does not support mutliple GPU very well, when i write this code, i only have one GPU, the mutiple GPU part are not well tested.
