### ISSUE TITLE
No module named 'dataset.video_augmentation_torch'

### ISSUE THREAD

**Issue by muxiddin19** [gswycf/SignGraph#2]
I faced another issue:

(signgraph) wsl@DESKTOP-CJL0ECN:/mnt/h/muhiddin/signgraph$ python main.py --device 0
Not using distributed mode
[0]
Loading model
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/wsl/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:12<00:00, 3.66MB/s]
learning rate conv2d=0.0001
learning rate conv1d=0.0001
learning rate temporal_model=0.0001
learning rate classifier=0.0001
Loading model finished.
Loading Dataprocessing
Traceback (most recent call last):
  File "/mnt/h/muhiddin/signgraph/main.py", line 302, in <module>
    processor = Processor(args)
  File "/mnt/h/muhiddin/signgraph/main.py", line 50, in __init__
    self.model, self.optimizer = self.loading()
  File "/mnt/h/muhiddin/signgraph/main.py", line 166, in loading
    self.load_data()
  File "/mnt/h/muhiddin/signgraph/main.py", line 227, in load_data
    self.feeder = import_class(self.arg.feeder)
  File "/mnt/h/muhiddin/signgraph/main.py", line 279, in import_class
    mod = importlib.import_module(components[0])
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/h/muhiddin/signgraph/dataset/__init__.py", line 1, in <module>
    from .video_augmentation_torch import *
ModuleNotFoundError: No module named 'dataset.video_augmentation_torch'

Where to get the required file? Can you please share it if you have one? Or is there another solution?

**Comment by muxiddin19** [comment]
I have made such changes in __init__.py, as there was only dataloader_video.py file, and I hope it will not cause another issue in the next stages:
from .video_augmentation_torch import *  --> from .dataloader_video import *
