### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by muxiddin19** [gswycf/SignGraph#5]
Hello! There is another issue related to CUDA while I train or test the model. I tried to decrease batc_size 4 --> 2, test_bacth_size 4 --> 2. However, there are no changes. I attached the related info and my device info too. Can you give your solution for this? Is my device is valid for this calculation, or should I use another much powerful machine?
Traceback (most recent call last):
  File "/mnt/h/muhiddin/signgraph/main.py", line 304, in <module>
    processor.start()
  File "/mnt/h/muhiddin/signgraph/main.py", line 109, in start
    train_wer = seq_eval(self.arg, self.data_loader["train_eval"], self.model, self.device,
  File "/mnt/h/muhiddin/signgraph/seq_scripts.py", line 68, in seq_eval
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in do_one_step
    data = pin_memory(data, device)
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 67, in pin_memory
    return [pin_memory(sample, device) for sample in data]  # Backwards compatibility.
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 67, in <listcomp>
    return [pin_memory(sample, device) for sample in data]  # Backwards compatibility.
  File "/home/wsl/miniconda3/envs/signgraph/lib/python3.9/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return data.pin_memory(device)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

![image](https://github.com/gswycf/SignGraph/assets/54941476/df0b4c26-3cf3-4ba6-8140-b0d656b6832a)

**Comment by gswycf** [comment]
Hi， Sorry for the late reply, try to set batch_size=1?

**Comment by gswycf** [comment]
> RuntimeError: Caught RuntimeError in pin memory thread for device 0.

or try set num_worker=0 or less 20
